In [3]:
import re
import math
import numpy as np

In [4]:
def read_input(infile):
    particles = []
    pidx = 0
    with open(infile, 'r') as inf:
        for line in inf.readlines():
            m = (re.match(r'p=<(-?\d+),(-?\d+),(-?\d+)>, v=<(-?\d+),(-?\d+),(-?\d+)>, a=<(-?\d+),(-?\d+),(-?\d+)>', line.strip()).groups())
            particles.append([pidx] + [int(v) for v in m])
            pidx += 1

    return particles

In [57]:
def sorter(p):
    return abs(p[7]) + abs(p[8]) + abs(p[9])

def find_closest_particle(particles):
    return sorted(particles, key=sorter)[0][0]

def pos(p, i, t):
    return p[1+i] + p[4+i]*t + 0.5*p[7+i]*t**2

def eliminate(particles):

    idx = []
    p = []
    v = []
    a = []

    for part in particles:
        idx.append(part[0])
        p.append(part[1:4])
        v.append(part[4:7])
        a.append(part[7:])

    idx = np.array(idx, dtype=int)
    p = np.array(p, dtype=int)
    v = np.array(v, dtype=int)
    a = np.array(a, dtype=int)

    for _ in range(5000):

        v += a
        p += v

        i, ii, inv, n = np.unique(p, axis=0, return_index=True, return_inverse=True, return_counts=True)

        w = ii[np.where(n == 1)]
        idx = idx[w]
        v = v[w]
        p = p[w]
        a = a[w]

    return len(idx)


420


In [58]:
print('*******\nPuzzle1\n*******\n')

print('Puzzle case\n-----------\n')

res = find_closest_particle(read_input('input20.txt'))

print(f'Particle closest to 0,0,0 in the long run is {res}')

assert res == 364

print('\n*******\nPuzzle2\n*******\n')

print('Test case\n---------\n')

res = eliminate(read_input('input20a.txt'))

print(f'{res} particles remain')

assert res == 1

print('\nPuzzle case\n-----------\n')

res = eliminate(read_input('input20.txt'))

print(f'{res} particles remain')

assert res == 420


*******
Puzzle1
*******

Puzzle case
-----------

Particle closest to 0,0,0 in the long run is 364

*******
Puzzle2
*******

Test case
---------

1
None particles remain


AssertionError: 

In [17]:
3*2 -6

0

x2 + v2*t + 0.5*a2*t**2 = x1 + v1*t + 0.5*a1*t**2
0.5*a1*t**2 - 0.5*a2*t**2 = x2 - x1 + v2*t - v1*t
t**2*0.5*(a1-a2) = t*(v2-v1)
t = 2* (v2-v1) / (a1-a2)


In [ ]:
2* (2-3) / 

(x2-x1) + (v2-v1)*t + 0.5*(a2-a1)*t**2 = 0
(-(v2-v1) +- sqrt((v2-v1)**2-2*(a2-a1)*(x2-x1))) / 2*(a2-a1) = t

x2+v2*t = x1+v1*t
(x2-x1) = (v1-v2)*t
(x2-x1)/(v1-v2) = t

In [21]:
(-4+6)/(3-2)

2.0

In [10]:
a = np.array([[1,1,1], [2,2,2]], dtype=int)
b = np.array([[3,4,5], [6,7,8]], dtype=int)

print(a)
print(b)
print(a+b)

[[1 1 1]
 [2 2 2]]
[[3 4 5]
 [6 7 8]]
[[ 4  5  6]
 [ 8  9 10]]
